/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package AplikasiGaji;

//import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
//import java.sql.ResultSet;
//import javax.swing.table.DefaultTableModel; 
/**
 *
 * @author lisa
 */
public class DataKaryawan extends javax.swing.JInternalFrame {

    /**
     * Creates new form DataKaryawan
     */
    SimpleDateFormat dateformat = new SimpleDateFormat("yyyy-MM-dd");
    public DataKaryawan() {
        initComponents();
        autonumber();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderButtonGroup = new javax.swing.ButtonGroup();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        keMenu1Button = new javax.swing.JButton();
        namaTxt = new javax.swing.JTextField();
        TTLDateChooser = new com.toedter.calendar.JDateChooser();
        LabelNIK = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AlamatTxt = new javax.swing.JTextArea();
        LabelTTL = new javax.swing.JLabel();
        LabelGender = new javax.swing.JLabel();
        LabelJabatan2 = new javax.swing.JLabel();
        LabelAlamat = new javax.swing.JLabel();
        jabatan2ComboBox = new javax.swing.JComboBox<>();
        NIKTxt = new javax.swing.JTextField();
        LakilakiRadioButton = new javax.swing.JRadioButton();
        PerempuanRadioButton = new javax.swing.JRadioButton();
        SimpanButton = new javax.swing.JButton();
        HapusButton = new javax.swing.JButton();
        LabelNama = new javax.swing.JLabel();

        setTitle("Data Karyawan");

        keMenu1Button.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        keMenu1Button.setForeground(new java.awt.Color(0, 42, 140));
        keMenu1Button.setText("Ke Menu Utama");
        keMenu1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keMenu1ButtonActionPerformed(evt);
            }
        });

        namaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaTxtActionPerformed(evt);
            }
        });

        LabelNIK.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelNIK.setForeground(new java.awt.Color(255, 255, 255));
        LabelNIK.setText("NIK");

        AlamatTxt.setColumns(20);
        AlamatTxt.setRows(5);
        jScrollPane1.setViewportView(AlamatTxt);

        LabelTTL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelTTL.setForeground(new java.awt.Color(255, 255, 255));
        LabelTTL.setText("Tanggal Lahir");

        LabelGender.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelGender.setForeground(new java.awt.Color(255, 255, 255));
        LabelGender.setText("Jenis Kelamin");

        LabelJabatan2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelJabatan2.setForeground(new java.awt.Color(255, 255, 255));
        LabelJabatan2.setText("Jabatan");

        LabelAlamat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelAlamat.setForeground(new java.awt.Color(255, 255, 255));
        LabelAlamat.setText("Alamat");

        jabatan2ComboBox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jabatan2ComboBox.setForeground(new java.awt.Color(255, 255, 255));
        jabatan2ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "== PILIH ==", "Manajer", "Operator", "Admin", "HRD", "Marketing", "Programmer" }));

        NIKTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NIKTxtActionPerformed(evt);
            }
        });

        genderButtonGroup.add(LakilakiRadioButton);
        LakilakiRadioButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LakilakiRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        LakilakiRadioButton.setText("Laki-Laki");

        genderButtonGroup.add(PerempuanRadioButton);
        PerempuanRadioButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PerempuanRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        PerempuanRadioButton.setText("Perempuan");

        SimpanButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        SimpanButton.setForeground(new java.awt.Color(0, 50, 168));
        SimpanButton.setText("Simpan");
        SimpanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanButtonActionPerformed(evt);
            }
        });

        HapusButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        HapusButton.setForeground(new java.awt.Color(0, 49, 165));
        HapusButton.setText("Hapus");
        HapusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusButtonActionPerformed(evt);
            }
        });

        LabelNama.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelNama.setForeground(new java.awt.Color(255, 255, 255));
        LabelNama.setText("Nama");

        jDesktopPane1.setLayer(keMenu1Button, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(namaTxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(TTLDateChooser, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(LabelNIK, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(LabelTTL, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(LabelGender, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(LabelJabatan2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(LabelAlamat, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jabatan2ComboBox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(NIKTxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(LakilakiRadioButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(PerempuanRadioButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(SimpanButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(HapusButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(LabelNama, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(SimpanButton)
                        .addGap(37, 37, 37)
                        .addComponent(HapusButton)
                        .addGap(38, 38, 38)
                        .addComponent(keMenu1Button))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelNIK)
                            .addComponent(LabelTTL)
                            .addComponent(LabelNama)
                            .addComponent(LabelGender)
                            .addComponent(LabelAlamat)
                            .addComponent(LabelJabatan2))
                        .addGap(29, 29, 29)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NIKTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TTLDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jabatan2ComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDesktopPane1Layout.createSequentialGroup()
                                    .addComponent(LakilakiRadioButton)
                                    .addGap(18, 18, 18)
                                    .addComponent(PerempuanRadioButton))))))
                .addGap(80, 80, 80))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNama)
                    .addComponent(namaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNIK)
                    .addComponent(NIKTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TTLDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelTTL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PerempuanRadioButton)
                    .addComponent(LakilakiRadioButton)
                    .addComponent(LabelGender))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelJabatan2)
                    .addComponent(jabatan2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelAlamat)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(keMenu1Button)
                    .addComponent(HapusButton)
                    .addComponent(SimpanButton))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaTxtActionPerformed

    private void NIKTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NIKTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NIKTxtActionPerformed

    private void HapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusButtonActionPerformed
            NIKTxt.setText("");
            namaTxt.setText("");
            //NoIDTxt.setText("");
            TTLDateChooser.setCalendar(null);
            AlamatTxt.setText("");
            jabatan2ComboBox.setSelectedIndex(0);
            LakilakiRadioButton.setSelected(false);
            PerempuanRadioButton.setSelected(false);
    }//GEN-LAST:event_HapusButtonActionPerformed

    private void keMenu1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keMenu1ButtonActionPerformed
        OptionMenu optionMenu1 = new OptionMenu();
        optionMenu1.setVisible(true);
        this.getDesktopPane().add(optionMenu1);
        this.dispose();
    }//GEN-LAST:event_keMenu1ButtonActionPerformed
    int id = 1;      
    private void autonumber(){
        try {
            Connection conn = ConnectionDb.connectDatabase();
            try (Statement stat = conn.createStatement()) {
                String sql = "SELECT * FROM datakaryawan ORDER BY No_ID DESC";
                try (ResultSet rs = stat.executeQuery(sql)) {
                    if (rs.next()) {
                        id = rs.getInt("No_ID");
                        id = id + 1;
                    }
                }
            }
        } catch (Exception e) {
            System.out.println("AUTONUMBER ERROR");
            e.printStackTrace();
        }
    }
    private void SimpanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanButtonActionPerformed
        String genderType = null;
        if (LakilakiRadioButton.isSelected()){
            genderType = "Laki-Laki";
        } else {
            genderType = "Perempuan";
        }
        try {
            String sql = "INSERT INTO datakaryawan (Nama, NIK, No_ID, Tanggal_Lahir, Jenis_Kelamin, Jabatan, Alamat) VALUES ('"
            + namaTxt.getText() + "','"
            + NIKTxt.getText() + "','"
            + id + "','"
            + dateformat.format(TTLDateChooser.getDate())+ "','"
            + genderType + "','"
            + jabatan2ComboBox.getSelectedItem() + "','"
            + AlamatTxt.getText() + "');";
        Connection conn = (Connection)ConnectionDb.connectDatabase();
        PreparedStatement pst = (PreparedStatement) conn.prepareStatement(sql);
        pst.execute();
        } catch (SQLException ex) {
            Logger.getLogger(DataKaryawan.class.getName()).log(Level.SEVERE,null,ex);
        }
        OptionMenu optionMenu = new OptionMenu();
        optionMenu.setVisible(true);
        this.getDesktopPane().add(optionMenu);
        this.dispose();
    }//GEN-LAST:event_SimpanButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AlamatTxt;
    private javax.swing.JButton HapusButton;
    private javax.swing.JLabel LabelAlamat;
    private javax.swing.JLabel LabelGender;
    private javax.swing.JLabel LabelJabatan2;
    private javax.swing.JLabel LabelNIK;
    private javax.swing.JLabel LabelNama;
    private javax.swing.JLabel LabelTTL;
    private javax.swing.JRadioButton LakilakiRadioButton;
    private javax.swing.JTextField NIKTxt;
    private javax.swing.JRadioButton PerempuanRadioButton;
    private javax.swing.JButton SimpanButton;
    private com.toedter.calendar.JDateChooser TTLDateChooser;
    private javax.swing.ButtonGroup genderButtonGroup;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jabatan2ComboBox;
    private javax.swing.JButton keMenu1Button;
    private javax.swing.JTextField namaTxt;
    // End of variables declaration//GEN-END:variables
}
