/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package AplikasiGaji;

import static AplikasiGaji.ConnectionDb.conn;
import static AplikasiGaji.ConnectionDb.pst;
import static AplikasiGaji.ConnectionDb.rs;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
//import java.sql.DriverManager;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
//import java.awt.HeadlessException;


/**
 *
 * @author lisa
 */

public class GajiKaryawan extends javax.swing.JInternalFrame {

    /**
     * Creates new form GajiKaryawan
     */
    
    SimpleDateFormat dateformat = new SimpleDateFormat("yyyy-MM-dd");
    public GajiKaryawan() {
        initComponents();
        autonumber();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        LabelTakHadir = new javax.swing.JLabel();
        lemburTxt = new javax.swing.JTextField();
        namaTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        takhadirTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jabatanComboBox = new javax.swing.JComboBox<>();
        tambahLemburTxt = new javax.swing.JTextField();
        LabelGajiP = new javax.swing.JLabel();
        LabelPotonganAbsen = new javax.swing.JLabel();
        LabelAsuransi = new javax.swing.JLabel();
        LabelTotal = new javax.swing.JLabel();
        gajiTxt = new javax.swing.JTextField();
        potonghadirTxt = new javax.swing.JTextField();
        asuransiTxt = new javax.swing.JTextField();
        totalTxt = new javax.swing.JTextField();
        hapusButton = new javax.swing.JButton();
        simpanButton = new javax.swing.JButton();
        hitungButton = new javax.swing.JButton();
        keMenu2Button = new javax.swing.JButton();
        cariIDButton = new javax.swing.JButton();
        LabelIDKaryawan = new javax.swing.JLabel();
        IDKaryawanTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        LabelNama = new javax.swing.JLabel();
        periodeGajiDateChooser = new com.toedter.calendar.JDateChooser();
        LabelJabatan = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setTitle("GAJI KARYAWAN");

        LabelTakHadir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelTakHadir.setForeground(new java.awt.Color(255, 255, 255));
        LabelTakHadir.setText("Jumlah Tak Hadir");

        lemburTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lemburTxtActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Jam");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tambahan Lembur");

        jabatanComboBox.setForeground(new java.awt.Color(0, 42, 140));
        jabatanComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "== PILIH ==", "Manajer", "Operator", "Admin", "HRD", "Marketing", "Programmer" }));
        jabatanComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jabatanComboBoxActionPerformed(evt);
            }
        });

        tambahLemburTxt.setEditable(false);

        LabelGajiP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelGajiP.setForeground(new java.awt.Color(255, 255, 255));
        LabelGajiP.setText("Gaji Pokok");

        LabelPotonganAbsen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelPotonganAbsen.setForeground(new java.awt.Color(255, 255, 255));
        LabelPotonganAbsen.setText("Potongan Kehadiran");

        LabelAsuransi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelAsuransi.setForeground(new java.awt.Color(255, 255, 255));
        LabelAsuransi.setText("Potongan Asuransi");

        LabelTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelTotal.setForeground(new java.awt.Color(255, 255, 255));
        LabelTotal.setText("Total Gaji");

        gajiTxt.setEditable(false);

        potonghadirTxt.setEditable(false);

        asuransiTxt.setEditable(false);
        asuransiTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asuransiTxtActionPerformed(evt);
            }
        });

        totalTxt.setEditable(false);

        hapusButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        hapusButton.setForeground(new java.awt.Color(0, 42, 140));
        hapusButton.setText("Hapus");
        hapusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusButtonActionPerformed(evt);
            }
        });

        simpanButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        simpanButton.setForeground(new java.awt.Color(0, 42, 140));
        simpanButton.setText("Simpan");
        simpanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanButtonActionPerformed(evt);
            }
        });

        hitungButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        hitungButton.setForeground(new java.awt.Color(0, 42, 140));
        hitungButton.setText("Hitung");
        hitungButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungButtonActionPerformed(evt);
            }
        });

        keMenu2Button.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        keMenu2Button.setForeground(new java.awt.Color(0, 42, 140));
        keMenu2Button.setText("Ke Menu Utama");
        keMenu2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keMenu2ButtonActionPerformed(evt);
            }
        });

        cariIDButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        cariIDButton.setForeground(new java.awt.Color(0, 42, 140));
        cariIDButton.setText("Cari ID");
        cariIDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariIDButtonActionPerformed(evt);
            }
        });

        LabelIDKaryawan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelIDKaryawan.setForeground(new java.awt.Color(255, 255, 255));
        LabelIDKaryawan.setText("ID Karyawan");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Periode");

        LabelNama.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelNama.setForeground(new java.awt.Color(255, 255, 255));
        LabelNama.setText("Nama");

        LabelJabatan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelJabatan.setForeground(new java.awt.Color(255, 255, 255));
        LabelJabatan.setText("Jabatan");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Lembur");

        jDesktopPane1.setLayer(LabelTakHadir, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lemburTxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(namaTxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(takhadirTxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jabatanComboBox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(tambahLemburTxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(LabelGajiP, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(LabelPotonganAbsen, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(LabelAsuransi, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(LabelTotal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(gajiTxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(potonghadirTxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(asuransiTxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(totalTxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(hapusButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(simpanButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(hitungButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(keMenu2Button, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(cariIDButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(LabelIDKaryawan, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(IDKaryawanTxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(LabelNama, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(periodeGajiDateChooser, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(LabelJabatan, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(hitungButton)
                        .addGap(27, 27, 27)
                        .addComponent(simpanButton)
                        .addGap(18, 18, 18)
                        .addComponent(hapusButton))
                    .addComponent(keMenu2Button)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelNama)
                            .addComponent(LabelJabatan)
                            .addComponent(LabelGajiP)
                            .addComponent(LabelIDKaryawan)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(25, 25, 25)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(namaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jabatanComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(gajiTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(IDKaryawanTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(periodeGajiDateChooser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(lemburTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)))
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelAsuransi)
                                    .addComponent(LabelTotal)
                                    .addComponent(LabelTakHadir)
                                    .addComponent(cariIDButton)
                                    .addComponent(jLabel4))
                                .addGap(29, 29, 29))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelPotonganAbsen)
                                .addGap(18, 18, 18)))
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(asuransiTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(potonghadirTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(takhadirTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(totalTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tambahLemburTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cariIDButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelIDKaryawan)
                            .addComponent(IDKaryawanTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)))
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(namaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelNama))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jabatanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelJabatan)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(potonghadirTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelPotonganAbsen))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(gajiTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelGajiP)
                                    .addComponent(asuransiTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelAsuransi))
                                .addGap(6, 6, 6)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(lemburTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel3))
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(periodeGajiDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1))))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(takhadirTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelTakHadir))
                        .addGap(68, 68, 68)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tambahLemburTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelTotal))
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hapusButton)
                            .addComponent(simpanButton)
                            .addComponent(hitungButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(keMenu2Button)))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int IDgaji = 1;      
    private void autonumber(){
        try {
            Connection conn = ConnectionDb.connectDatabase();
            try (Statement stat = conn.createStatement()) {
                String sql = "SELECT * FROM gaji_karyawan ORDER BY ID_Gaji DESC";
                try (ResultSet rs = stat.executeQuery(sql)) {
                    if (rs.next()) {
                        IDgaji = rs.getInt("ID_Gaji");
                        IDgaji = IDgaji + 1;
                    }
                }
            }
        } catch (Exception e) {
            System.out.println("AUTONUMBER ERROR");
            e.printStackTrace();
        }
    }
    private void asuransiTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asuransiTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asuransiTxtActionPerformed

    private void jabatanComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jabatanComboBoxActionPerformed
        switch(jabatanComboBox.getSelectedIndex()){
            case 0:
                gajiTxt.setText("");
                break;
            
            case 1:
                gajiTxt.setText("9000000");
                break;
                
            case 2:
                gajiTxt.setText("4500000");
                break;
                
            case 3:
                gajiTxt.setText("3500000");
                break;
                
            case 4:
                gajiTxt.setText("7500000");
                break;
                
            case 5:
                gajiTxt.setText("5500000");
                break;
                
            default:
                gajiTxt.setText("10000000");
                break;
        }
                
    }//GEN-LAST:event_jabatanComboBoxActionPerformed

    private void hapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusButtonActionPerformed
        IDKaryawanTxt.setText("");
        namaTxt.setText("");
        jabatanComboBox.setSelectedIndex(0);
        periodeGajiDateChooser.setCalendar(null);
        takhadirTxt.setText("");
        lemburTxt.setText("");
        tambahLemburTxt.setText("");
        gajiTxt.setText("");
        potonghadirTxt.setText("");
        asuransiTxt.setText("");
        totalTxt.setText("");
    }//GEN-LAST:event_hapusButtonActionPerformed

    private void hitungButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungButtonActionPerformed
        if(gajiTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Data belum lengkap");
        } else if(takhadirTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Data belum lengkap");
        } else if(namaTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Data belum lengkap");
        //} else if(IDGajiTxt.getText().isEmpty()){
            //JOptionPane.showMessageDialog(null, "Data belum lengkap");
        }
          else {
            float jumlahTakHadir = Long.parseLong(takhadirTxt.getText()),
                gajiPokok = Long.parseLong(gajiTxt.getText()),
                jamLembur = Long.parseLong(lemburTxt.getText()),
                lembur, potonganKehadiran, potonganAsuransi, gajiTotal;
            lembur = jamLembur * 3/2 * 1/173 * gajiPokok;
            potonganKehadiran = (jumlahTakHadir / 20) * gajiPokok;
            potonganAsuransi = gajiPokok/100; 
            gajiTotal = gajiPokok + lembur - potonganKehadiran - potonganAsuransi;
            potonghadirTxt.setText(""+potonganKehadiran);
            asuransiTxt.setText(""+potonganAsuransi);
            tambahLemburTxt.setText(""+lembur);
            totalTxt.setText(""+gajiTotal);
        }
    
        
    }//GEN-LAST:event_hitungButtonActionPerformed

    private void simpanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanButtonActionPerformed
        try {
            String sql = "INSERT INTO gaji_karyawan (ID_Karyawan, Nama_Karyawan, ID_Gaji, Jabatan, Gaji_Pokok, Lembur, Periode_Gaji, Jumlah_Tak_Hadir, Potongan_Kehadiran, Potongan_Asuransi, Gaji_Total) VALUES ('"
            + IDKaryawanTxt.getText() + "','"
            + namaTxt.getText() + "','"
            + IDgaji + "','"
            + jabatanComboBox.getSelectedItem() + "','"
            + gajiTxt.getText() + "','"
            + tambahLemburTxt.getText() + "','"
            + dateformat.format(periodeGajiDateChooser.getDate()) + "','"
            + takhadirTxt.getText() + "','"
            + potonghadirTxt.getText() + "','"
            + asuransiTxt.getText() + "','"
            + totalTxt.getText() + "');";
        Connection conn = (Connection)ConnectionDb.connectDatabase();
        PreparedStatement pst = (PreparedStatement) conn.prepareStatement(sql);
        pst.execute();
        } catch (SQLException ex) {
            Logger.getLogger(GajiKaryawan.class.getName()).log(Level.SEVERE,null,ex);
        }
        OptionMenu optionMenu = new OptionMenu();
        optionMenu.setVisible(true);
        this.getDesktopPane().add(optionMenu);
        this.dispose();
    }//GEN-LAST:event_simpanButtonActionPerformed

    private void keMenu2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keMenu2ButtonActionPerformed
        OptionMenu optionMenu2 = new OptionMenu();
        optionMenu2.setVisible(true);
        this.getDesktopPane().add(optionMenu2);
        this.dispose();
    }//GEN-LAST:event_keMenu2ButtonActionPerformed

    private void cariIDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariIDButtonActionPerformed
        try {
            String id = IDKaryawanTxt.getText();
            pst = conn.prepareStatement("select * from datakaryawan where No_ID=?");
            pst.setString(1, id);
            rs = pst.executeQuery();
            if (rs.next() == true) {
                namaTxt.setText(rs.getString(1));
                jabatanComboBox.setSelectedItem(rs.getString(6));
            }
        } catch (SQLException ex) {
            Logger.getLogger(GajiKaryawan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cariIDButtonActionPerformed

    private void lemburTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lemburTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lemburTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDKaryawanTxt;
    private javax.swing.JLabel LabelAsuransi;
    private javax.swing.JLabel LabelGajiP;
    private javax.swing.JLabel LabelIDKaryawan;
    private javax.swing.JLabel LabelJabatan;
    private javax.swing.JLabel LabelNama;
    private javax.swing.JLabel LabelPotonganAbsen;
    private javax.swing.JLabel LabelTakHadir;
    private javax.swing.JLabel LabelTotal;
    private javax.swing.JTextField asuransiTxt;
    private javax.swing.JButton cariIDButton;
    private javax.swing.JTextField gajiTxt;
    private javax.swing.JButton hapusButton;
    private javax.swing.JButton hitungButton;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<String> jabatanComboBox;
    private javax.swing.JButton keMenu2Button;
    private javax.swing.JTextField lemburTxt;
    private javax.swing.JTextField namaTxt;
    private com.toedter.calendar.JDateChooser periodeGajiDateChooser;
    private javax.swing.JTextField potonghadirTxt;
    private javax.swing.JButton simpanButton;
    private javax.swing.JTextField takhadirTxt;
    private javax.swing.JTextField tambahLemburTxt;
    private javax.swing.JTextField totalTxt;
    // End of variables declaration//GEN-END:variables

    private PreparedStatement setString(int i, String id) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
