/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package AplikasiGaji;

//import com.mysql.cj.protocol.Resultset;
//import java.lang.System.Logger;
//import java.lang.System.Logger.Level;
//import java.sql.SQLException; 
//import javax.swing.table.DefaultTableModel;
//import com.mysql.jdbc.Statement;
//import com.mysql.cj.xdevapi.Statement;
import static AplikasiGaji.ConnectionDb.conn;
import java.sql.Statement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author USER
 */
public class RekapData extends javax.swing.JInternalFrame {
    
    /**
     * Creates new form RekapData
     */
    public RekapData() {
        initComponents();
        showTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        keMenu3Button = new javax.swing.JButton();
        nama2Label = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        carinamaTxt = new javax.swing.JTextField();
        cariButton = new javax.swing.JButton();
        hapusButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        rekapdatakaryawanTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 255, 255));
        setTitle("Rekap Data");

        keMenu3Button.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        keMenu3Button.setForeground(new java.awt.Color(0, 42, 140));
        keMenu3Button.setText("Ke Menu Utama");
        keMenu3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keMenu3ButtonActionPerformed(evt);
            }
        });

        nama2Label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nama2Label.setForeground(new java.awt.Color(255, 255, 255));
        nama2Label.setText("Nama Karyawan");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DATA KARYAWAN");

        cariButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        cariButton.setForeground(new java.awt.Color(0, 42, 140));
        cariButton.setText("Cari");
        cariButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariButtonActionPerformed(evt);
            }
        });

        hapusButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        hapusButton.setForeground(new java.awt.Color(0, 42, 140));
        hapusButton.setText("Hapus");
        hapusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusButtonActionPerformed(evt);
            }
        });

        rekapdatakaryawanTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "NIK", "No ID", "Tanggal Lahir", "Jenis Kelamin", "Jabatan", "Alamat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(rekapdatakaryawanTable);

        jDesktopPane1.setLayer(keMenu3Button, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(nama2Label, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(carinamaTxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(cariButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(hapusButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(nama2Label)
                        .addGap(33, 33, 33)
                        .addComponent(carinamaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(cariButton)
                        .addGap(18, 18, 18)
                        .addComponent(hapusButton)
                        .addGap(18, 18, 18)
                        .addComponent(keMenu3Button))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(jLabel3)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carinamaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nama2Label))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cariButton)
                    .addComponent(hapusButton)
                    .addComponent(keMenu3Button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void keMenu3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keMenu3ButtonActionPerformed
        OptionMenu optionMenu3 = new OptionMenu();
        optionMenu3.setVisible(true);
        this.getDesktopPane().add(optionMenu3);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_keMenu3ButtonActionPerformed

    private void cariButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariButtonActionPerformed
        try {
                String nama = carinamaTxt.getText();
                String queryNama = "SELECT * FROM datakaryawan WHERE Nama = '" + nama + "'";
                Statement stat = conn.createStatement();
                ResultSet rs = stat.executeQuery(queryNama);
                // menampilkan data pada komponen tabel
                DefaultTableModel model = (DefaultTableModel) rekapdatakaryawanTable.getModel();
                model.setRowCount(0);
                while (rs.next()) {
                    Object[] row = { rs.getString("Nama"),rs.getString("NIK"),rs.getString("No_ID"),
                            rs.getString("Tanggal_Lahir"),rs.getString("Jenis_Kelamin"),
                            rs.getString("Jabatan"),rs.getString("Alamat")};
                    model.addRow(row);
                }
            } catch (SQLException ex) {
                Logger.getLogger(RekapData.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_cariButtonActionPerformed

    private void hapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusButtonActionPerformed
         try {
                int selectedRow = rekapdatakaryawanTable.getSelectedRow();

                // mengambil nilai dari kolom ID pada baris yang dipilih
                String nama = rekapdatakaryawanTable.getValueAt(selectedRow, 0).toString();

                // membuat query SQL untuk menghapus data dari tabel
                String query = "DELETE FROM datakaryawan WHERE Nama = '" + nama + "'";

                // membuat statement dan mengeksekusi query SQL
                Statement stat = conn.createStatement();
                stat.executeUpdate(query);

                // menghapus baris pada tabel yang telah dihapus dari database
                DefaultTableModel model = (DefaultTableModel) rekapdatakaryawanTable.getModel();
                model.removeRow(selectedRow);
            } catch (SQLException ex) {
                Logger.getLogger(RekapData.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_hapusButtonActionPerformed
    
    public void showTable(){
        try{
            //Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3307/data_karyawan","user","pass");
            Statement stat = (Statement)ConnectionDb.connectDatabase().createStatement();
            String sql = "select * from datakaryawan";
            ResultSet rs = stat.executeQuery(sql);
            DefaultTableModel tableModel;
            tableModel = (DefaultTableModel)rekapdatakaryawanTable.getModel();
            while(rs.next()){
                tableModel.addRow(new Object[] {
                   rs.getString(1),rs.getString(2),rs.getString(3),
                   rs.getString(4),rs.getString(5),rs.getString(6),
                   rs.getString(7)
                });
            }
        } catch (SQLException ex) {
            Logger.getLogger(DataKaryawan.class.getName()).log(Level.SEVERE,null,ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cariButton;
    private javax.swing.JTextField carinamaTxt;
    private javax.swing.JButton hapusButton;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton keMenu3Button;
    private javax.swing.JLabel nama2Label;
    private javax.swing.JTable rekapdatakaryawanTable;
    // End of variables declaration//GEN-END:variables
}
